set -o vi

PATH=$PATH:/opt/local/bin

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export DOCKER_HOST=tcp://192.168.59.103:2376

export DOCKER_CERT_PATH=/Users/msl/.boot2docker/certs/boot2docker-vm

export DOCKER_TLS_VERIFY=1

export DOCKER_ENV_FILE=$CONFIG_FILES_HOME/docker_env_file.sh

source /Users/robin/perl5/perlbrew/etc/bashrc
