#!/usr/bin/env zsh -x

# Greeting
###############################################################################
DOTFILES_HOME=~/Programming/robin/zsh/projects/dotfiles
source $DOTFILES_HOME/dotfiles-base/zsh/colors.zsh

echo "$(brightwhite)I $(brightyellow)am $(brightcyan awesome)"
# Or alternatively:
# echo "$(brightwhite I)$(brightyellow " am ")$(brightcyan awesome)"


# Third-party ZSH framework
###############################################################################
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for config_file ($HOME/.framework/zsh/*.zsh) source $config_file


# Environment variables
###############################################################################
source $DOTFILES_HOME/dotfiles-base/zsh/env_variables.zsh


# Functions
###############################################################################
source $DOTFILES_HOME/dotfiles-base/zsh/functions.zsh


# Aliases
###############################################################################
source $DOTFILES_HOME/dotfiles-base/zsh/aliases.zsh


# Path
###############################################################################
source path.zsh


# ZSH Options
###############################################################################

# Stop correcting me when commands are correct!!
unsetopt correct

# `cd` into directory by only typing directory name
setopt autocd
# Vim-style editing on command line
setopt vi
# Shares history between shells instantaneously
setopt share_history


prompt robin


# Development
###############################################################################

## Python
#########
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

if [[ "$HOSTNAME" == "$VENUS_HOSTNAME" ]]
then
	pythonbrew use 2.7 2> /dev/null
else
	pythonbrew use 2.7 2> /dev/null
fi


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 


## Ruby
#######
# `rvm reset` is the magic secret command that fixes the path errors!!
ruby="2.1.1"
rvm use ruby-"$ruby"


## OCaml
########
# OPAM configuration
. /Users/msl/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true


# OS-X Defaults
#########################################################################

defaults write com.apple.Safari AlwaysShowTabBar -bool NO

defaults write com.apple.Finder AppleShowAllFiles NO 2> /dev/null

# http://www.tekrevue.com/tip/how-to-customize-screenshot-options-in-mac-os-x/
# killall SystemUIServer
defaults write com.apple.screencapture location $SCREENSHOTS_HOME 2> /dev/null

defaults write com.apple.screencapture name $HOSTNAME
# defaults write com.apple.screencapture type png

defaults write -g ApplePersistence -bool no 2> /dev/null

chflags nohidden ~/Library/ 2> /dev/null

# Speed at which Dock auto-hides
# defaults write com.apple.dock autohide-time-modifier -float 0.0
