#!/usr/bin/env zsh -x


source $ZSHCOLORS_PATH


# Third-party ZSH framework
###############################################################################
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

for config_file ($HOME/.framework/zsh/*.zsh) source $config_file


# Environment variables
###############################################################################
source $ZDOT_HOME/env_variables.zsh


# Functions
###############################################################################
source $ZDOT_HOME/functions.zsh


# Aliases
###############################################################################
source $ZDOT_HOME/aliases.zsh


# Path
###############################################################################
source $ZDOT_HOME/path.zsh


# Greeting
###############################################################################
echo "$(brightwhite)I $(brightyellow)am $(brightcyan awesome)"
if [[ $SAYCMD == 1 ]]
then
  say "I am awesome"
fi
# Or alternatively:
# echo "$(brightwhite I)$(brightyellow " am ")$(brightcyan awesome)"


# ZSH Options
###############################################################################
source $ZDOT_HOME/options.zsh


# Prompt
###############################################################################
prompt robin


# Development
###############################################################################

## Python
#########
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

if [[ "$HOSTNAME" == "$VENUS_HOSTNAME" ]]
then
	pythonbrew use 2.7 2> /dev/null
else
	pythonbrew use 2.7 2> /dev/null
fi


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 


## Ruby
#######
# `rvm reset` is the magic secret command that fixes the path errors!!
ruby="2.1.1"
rvm use ruby-"$ruby"


## OCaml
########
# OPAM configuration
. /Users/msl/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
